services:
# https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ddd.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports: # uses 5672 internally
      - 15673:15672

  frontdesk-db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
        SA_PASSWORD: "P@ssW0rd!"
        ACCEPT_EULA: "Y"

  frontdesk-api:
    build:
      context: .
      dockerfile: ./FrontDesk/src/FrontDesk.Api/Dockerfile
    image: ddd.frontdesk.api
    container_name: ddd.frontdesk.api
    ports:
      - 5200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://+"
    restart: on-failure
    depends_on:
      - rabbitmq
      - frontdesk-db

  clinicmanagement-db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
        SA_PASSWORD: "P@ssW0rd!"
        ACCEPT_EULA: "Y"

  clinicmanagement-api:
    build:
      context: .
      dockerfile: ./ClinicManagement/src/ClinicManagement.Api/Dockerfile
    image: ddd.clinicmanagement.api
    container_name: ddd.clinicmanagement.api
    ports:
      - 6200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://+"
    restart: on-failure
    depends_on:
      - rabbitmq
      - frontdesk-db

  mailserver:
    image: jijiechen/papercut:latest
    container_name: ddd.papercut
    ports: # exposes port 25 internally
    - 37409:37408

  vet-clinic-public:
    build:
      context: .
      dockerfile: ./VetClinicPublic/src/VetClinicPublic/Dockerfile
    image: ddd.vet-clinic-public
    container_name: ddd.vet-clinic.public
    ports:
      - 7100:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://+"
    restart: on-failure
    depends_on:
      - mailserver
